language:
  - cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # - llvm-toolchain-precise-3.7
os:
  - linux

# install:
#   - sudo apt-get install libgtest-dev
#   - pip install --user cpp-coveralls

script:
  - cd build
  - cmake ../src
  - make
  - ./tests/unittests

after_success:
  - coveralls --root ../src -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false